### ISSUE TITLE
Do you need any help with this project?

### ISSUE THREAD

**Issue by RKALM** [buckyroberts/JavaScript-Lessons#1]
I am watching your repository since you started it, and i can understand the whole project.
But i have to ask. Do you believe that you will need help somehow on your project?
Bit CSS decoration maybe or something like that? :)
Best Regards
Robert.

**Comment by buckyroberts** [comment]
I don't want to do too much CSS related. I want to keep the demos as simple as possible so I can just illustrate the basic, core concepts. If you'd like, you can work on the READMEs for the lessons.

**Comment by RKALM** [comment]
The idea is great. I will see what can i do :)

**Comment by buckyroberts** [comment]
Thanks :-)
